### PR TITLE
Upgrade to Use Doctrine DAO

### LINKED ISSUE #2: Bug with class WebPA_Tool
Hi Steven,

Andrew Millington said this is probably the best place to report bugs.

I have tried installing the lti tool with the latest version of webpa and get the following error:

`Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in /var/www/html/WebPA/src/mod/lti/tool.php on line 46`

### PR DESCRIPTION
**Pull request by Sephster**
This PR upgrades the WebPA LTI connection to use the Doctrine DBAL connection provided by WebPA instead of the old DAO object.

It also fixes #2.

### CODE REVIEW

**Comment by Sephster** [comment]
@spvickers one thing to flag is that in admin/share/generate there were two variables that used the DB escape function. This function no longer exists in the DAO so I had to remove it but wanted to flag in case it causes any security issues.

**Comment by spvickers** [comment]
Thanks for the updates; I will try to make these changes whilst maintaining backward compatibility with previous releases of WebPA.

**Comment by spvickers** [comment]
Sorry, looks like I forgot to sort this; will take a look shortly.

**Comment by spvickers** [comment]
Thanks for these changes; I think they have all been included in version 3.2.0 released in April.

**Pull request closed without merging**
